/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author proxc
 */
public class Empleados extends javax.swing.JFrame {
int i=0;
    /**
     * Creates new form Home_Data
     */
    public Empleados() {
         try {
            this.cn = cc.conexion();
        } catch (InstantiationException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        mostrardatos("");
        this.setLocationRelativeTo(null);

    }
    conexion cc = new conexion();
    Connection cn;
  void mostrardatos(String valor) {
      String xd;
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id empleado");
        modelo.addColumn("Nombre");
        modelo.addColumn("Edad");
        modelo.addColumn("Fecha de nacimiento");
        modelo.addColumn("Sueldo semanal");
        tbJuegos.setModel(modelo);
        String sql = "";
        if (valor.equals("")) {
            sql = "SELECT * FROM empleadosbd";
        } else {
            sql = "SELECT * FROM empleadosbd WHERE Id_empleado='" + valor + "'";
        }
        String[] datos = new String[5];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                xd = rs.getString(1);
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
 

                modelo.addRow(datos);
            }
            tbJuegos.setModel(modelo);
            if (modelo.getDataVector().isEmpty()) 
                JOptionPane.showMessageDialog(null, "No se encontro el producto");
            
        } catch (SQLException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        TXTIDEMPLEADO = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXTNOMBRE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TXTEDAD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TXTFNACIMIENTO = new javax.swing.JTextField();
        TXTSUELDO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        Mostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbJuegos = new javax.swing.JTable();
        Regresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        actualizar = new javax.swing.JButton();

        jPopupMenu1.setToolTipText("");

        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem3.setText("Modificar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Muebles");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TXTIDEMPLEADO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTIDEMPLEADOMousePressed(evt);
                yih(evt);
            }
        });
        getContentPane().add(TXTIDEMPLEADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 110, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 118, 233));
        jLabel1.setText("Id empleado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 104, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 118, 233));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 146, -1, -1));
        getContentPane().add(TXTNOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 110, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(45, 118, 233));
        jLabel8.setText("Edad");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        getContentPane().add(TXTEDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 110, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(45, 118, 233));
        jLabel9.setText("Fecha de nacimiento");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        getContentPane().add(TXTFNACIMIENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 110, -1));

        TXTSUELDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTSUELDOActionPerformed(evt);
            }
        });
        getContentPane().add(TXTSUELDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 110, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 118, 233));
        jLabel4.setText("Sueldo semanal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        guardar.setBackground(new java.awt.Color(255, 255, 255));
        guardar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        guardar.setForeground(new java.awt.Color(45, 118, 233));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 100, -1));

        Limpiar.setBackground(new java.awt.Color(255, 255, 255));
        Limpiar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(45, 118, 233));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 100, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(45, 118, 233));
        jLabel11.setText("Buscar por id:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 332, -1, -1));
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 330, 141, -1));

        buscar.setBackground(new java.awt.Color(255, 255, 255));
        buscar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(45, 118, 233));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        Mostrar.setBackground(new java.awt.Color(255, 255, 255));
        Mostrar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Mostrar.setForeground(new java.awt.Color(45, 118, 233));
        Mostrar.setText("Mostrar tabla completa");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });
        getContentPane().add(Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        tbJuegos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbJuegos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbJuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbJuegos.setColumnSelectionAllowed(true);
        tbJuegos.setComponentPopupMenu(jPopupMenu1);
        tbJuegos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbJuegos.setSelectionBackground(new java.awt.Color(153, 204, 255));
        jScrollPane1.setViewportView(tbJuegos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 382, 922, 246));

        Regresar.setBackground(new java.awt.Color(255, 255, 255));
        Regresar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Regresar.setForeground(new java.awt.Color(45, 118, 233));
        Regresar.setText("Regresar al menu principal");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 672, -1, -1));

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/group_52px_1.png"))); // NOI18N
        jLabel15.setText("Empleados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel15)
                .addContainerGap(732, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel15)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 962, -1));

        actualizar.setBackground(new java.awt.Color(255, 255, 255));
        actualizar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        actualizar.setForeground(new java.awt.Color(45, 118, 233));
        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO empleadosbd (Id_empleado, Nombre, Edad, Fecha_nacimiento , Sueldo_semanal) VALUES (?,?,?,?,?)");
            pst.setString(1, TXTIDEMPLEADO.getText());
            pst.setString(2, TXTNOMBRE.getText());
            pst.setString(3, TXTEDAD.getText());
            pst.setString(4, TXTFNACIMIENTO.getText());
            pst.setString(5, TXTSUELDO.getText());
  
            System.out.println("Deberia Funcionar");
            int i = pst.executeUpdate();
            if (i > 0) {
                JOptionPane.showMessageDialog(null, "Se guardo correctamente");
                mostrardatos("");
            }
        } catch (Exception e) {
            System.out.print("Error al actualizar: " + e.getMessage());
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
      
        i=0;
        TXTIDEMPLEADO.setText("");
        TXTNOMBRE.setText("");
        TXTSUELDO.setText("");
        TXTEDAD.setText("");
        TXTFNACIMIENTO.setText("");
        TXTIDEMPLEADO.setEnabled(true);
    }//GEN-LAST:event_LimpiarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        mostrardatos(txtBuscar.getText());
    }//GEN-LAST:event_buscarActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        // TODO add your handling code here:
        mostrardatos("");
    }//GEN-LAST:event_MostrarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Home().show();
    }//GEN-LAST:event_RegresarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int fila = tbJuegos.getSelectedRow();
        String cod = "";
        cod = tbJuegos.getValueAt(fila, 0).toString();
        int salida;
        salida = JOptionPane.showConfirmDialog(this, "¿Seguro/a que deseas eliminarlo?", "Confirmar", JOptionPane.OK_CANCEL_OPTION);

        if (salida == 0) {
            //instrucciones
            try {
                PreparedStatement pst = cn.prepareStatement("DELETE FROM empleadosbd WHERE Id_empleado='" + cod + "'");
                pst.executeUpdate();
                mostrardatos("");

            } catch (Exception e) {
                System.out.println("no se pudo eliminar" + e);
            }
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        i=1;
           TXTIDEMPLEADO.setEditable(false);
        int fila = tbJuegos.getSelectedRow();
        if (fila >= 0) {
            TXTIDEMPLEADO.setText(tbJuegos.getValueAt(fila, 0).toString());
            TXTNOMBRE.setText(tbJuegos.getValueAt(fila, 1).toString());
            TXTEDAD.setText(tbJuegos.getValueAt(fila, 2).toString());
            TXTFNACIMIENTO.setText(tbJuegos.getValueAt(fila, 3).toString());
            TXTSUELDO.setText(tbJuegos.getValueAt(fila, 4).toString());

        } else {
            JOptionPane.showMessageDialog(null, "no selecciono fila");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void TXTSUELDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTSUELDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTSUELDOActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        TXTIDEMPLEADO.setEditable(true);
        try {
         
            PreparedStatement pst = cn.prepareStatement("UPDATE empleadosbd SET Id_empleado = ?, " + "Nombre = ?,"
                    + "Edad= ?,"
                    + "Fecha_nacimiento = ?,"
                    + "Sueldo_semanal = ?"
                    + "WHERE Id_empleado = '" + TXTIDEMPLEADO.getText() + "'");
            PreparedStatement pst2 = cn.prepareStatement("SELECT tipo FROM usuarios WHERE nombre = '$usuario'");
            pst.setString(1, TXTIDEMPLEADO.getText());
            pst.setString(2, TXTNOMBRE.getText());
            pst.setString(3, TXTEDAD.getText());
            pst.setString(4, TXTFNACIMIENTO.getText());
            pst.setString(5, TXTSUELDO.getText());
   
            System.out.println("Deberia Funcionar");
            int i = pst.executeUpdate();
            if (i > 0) {
                JOptionPane.showMessageDialog(null, "Se guardo correctamente");
                mostrardatos("");
            }
        } catch (Exception e) {
            System.out.print("Error al actualizar: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "no se puede modificar Id");
            
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void TXTIDEMPLEADOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTIDEMPLEADOMousePressed
        // TODO add your handling code here:
        if(evt.getSource()==TXTIDEMPLEADO && i==1){
            JOptionPane.showMessageDialog(null, "no se puede modificar Id");
        }
    }//GEN-LAST:event_TXTIDEMPLEADOMousePressed

    private void yih(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yih
        // TODO add your handling code here:
    }//GEN-LAST:event_yih
    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(197, 197, 197));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(240, 240, 240));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Mostrar;
    private javax.swing.JButton Regresar;
    private javax.swing.JTextField TXTEDAD;
    private javax.swing.JTextField TXTFNACIMIENTO;
    private javax.swing.JTextField TXTIDEMPLEADO;
    private javax.swing.JTextField TXTNOMBRE;
    private javax.swing.JTextField TXTSUELDO;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton buscar;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbJuegos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
    
}
