/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author proxc
 */
public class Pedidos extends javax.swing.JFrame {

    int i = 0;

    /**
     * Creates new form Home_Data
     */
    public Pedidos() {
        try {
            this.cn = cc.conexion();
        } catch (InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        mostrardatos("");
        this.setLocationRelativeTo(null);

    }

    void mostrardatos(String valor) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id pedido");
        modelo.addColumn("Mueble");
        modelo.addColumn("Estilo");
        modelo.addColumn("Color");
        modelo.addColumn("Tipo de madera");
        modelo.addColumn("Estado");
        modelo.addColumn("Destino");


        tbPedidos.setModel(modelo);
        String sql = "";
        if (valor.equals("")) {
            sql = "SELECT * FROM pedidos_db";
        } else {
            sql = "SELECT * FROM pedidos_db WHERE Id_pedido='" + valor + "'";
        }
        String[] datos = new String[7];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = Clean(rs.getString(1));
                datos[1] = Clean(rs.getString(2));
                datos[2] = Clean(rs.getString(3));
                datos[3] = Clean(rs.getString(4));
                datos[4] = Clean(rs.getString(5));
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);

                modelo.addRow(datos);
            }
            tbPedidos.setModel(modelo);
            if (modelo.getDataVector().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No se encontro el pedido");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        TXTIDP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXTMUEBLE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TXTESTILO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TXTCOLOR = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        Mostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPedidos = new javax.swing.JTable();
        Regresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        actualizar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTTIPO = new javax.swing.JTextField();
        TXTDESTINO = new javax.swing.JTextField();
        Estado = new javax.swing.JComboBox<>();

        jPopupMenu1.setToolTipText("");

        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem3.setText("Modificar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedidos");
        setBackground(new java.awt.Color(255, 255, 255));

        TXTIDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTIDPMousePressed(evt);
                yih(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 118, 233));
        jLabel1.setText("Id Pedido");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 118, 233));
        jLabel2.setText("Mueble");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(45, 118, 233));
        jLabel8.setText("Estilo");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(45, 118, 233));
        jLabel9.setText("Color");

        guardar.setBackground(new java.awt.Color(255, 255, 255));
        guardar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        guardar.setForeground(new java.awt.Color(45, 118, 233));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        Limpiar.setBackground(new java.awt.Color(255, 255, 255));
        Limpiar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(45, 118, 233));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(45, 118, 233));
        jLabel11.setText("Buscar por id:");

        buscar.setBackground(new java.awt.Color(255, 255, 255));
        buscar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(45, 118, 233));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        Mostrar.setBackground(new java.awt.Color(255, 255, 255));
        Mostrar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Mostrar.setForeground(new java.awt.Color(45, 118, 233));
        Mostrar.setText("Mostrar tabla completa");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        tbPedidos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbPedidos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbPedidos.setColumnSelectionAllowed(true);
        tbPedidos.setComponentPopupMenu(jPopupMenu1);
        tbPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbPedidos.setSelectionBackground(new java.awt.Color(153, 204, 255));
        jScrollPane1.setViewportView(tbPedidos);

        Regresar.setBackground(new java.awt.Color(255, 255, 255));
        Regresar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Regresar.setForeground(new java.awt.Color(45, 118, 233));
        Regresar.setText("Regresar al menu principal");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/list_64rpx.png"))); // NOI18N
        jLabel15.setText("Pedidos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        actualizar.setBackground(new java.awt.Color(255, 255, 255));
        actualizar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        actualizar.setForeground(new java.awt.Color(45, 118, 233));
        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(45, 118, 233));
        jLabel10.setText("Tipo de madera");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 118, 233));
        jLabel3.setText("Estado");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 118, 233));
        jLabel4.setText("Destino");

        TXTDESTINO.setEditable(false);
        TXTDESTINO.setText("Muebleria_Paulo");
        TXTDESTINO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TXTDESTINOMousePressed(evt);
            }
        });

        Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pedido", "Pendiente", "En proceso", "Finalizado", "Entregado", "Cancelado" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel10))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(TXTCOLOR, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TXTTIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(buscar)
                                                .addGap(28, 28, 28)
                                                .addComponent(Mostrar))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(59, 59, 59)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                            .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(33, 33, 33))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(TXTDESTINO, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(16, 16, 16)))
                                                .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(TXTESTILO, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TXTIDP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TXTMUEBLE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)))))
                            .addComponent(jLabel8))
                        .addGap(300, 300, 300))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(425, 425, 425)
                            .addComponent(Regresar))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Limpiar)
                                    .addComponent(guardar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TXTMUEBLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(TXTDESTINO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TXTESTILO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(TXTCOLOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTIDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actualizar)
                    .addComponent(jLabel10)
                    .addComponent(TXTTIPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar)
                    .addComponent(Mostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Regresar)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO pedidos_db (Id_pedido, Mueble, Estilo, Color, Tipo_madera, Estado, Destino) VALUES (?,?,?,?,?,?,?)");
            pst.setString(1, TXTIDP.getText());
            pst.setString(2, TXTMUEBLE.getText());
            pst.setString(3, TXTESTILO.getText());
            pst.setString(4, TXTCOLOR.getText());
            pst.setString(5, TXTTIPO.getText());
            pst.setString(6, Estado.getSelectedItem().toString());
            pst.setString(7, TXTDESTINO.getText());
            
            String mensaje = "INSERT INTO pedidos_db (Id_pedido, Mueble, Estilo, Color, Tipo_madera, Estado, Destino) VALUES ( '"+TXTIDP.getText()+"','"+ TXTMUEBLE.getText()+"','"+TXTESTILO.getText()+"','"+TXTCOLOR.getText()
                    +"','"+TXTTIPO.getText()+"','"+Estado.getSelectedItem().toString()+"','"+TXTDESTINO.getText()+"')";
            int i = pst.executeUpdate();
            if (i > 0) {
                Cliente c3 = new Cliente(5001, "192.168.0.106", mensaje);
                Thread t3 = new Thread(c3);
                t3.start();
                JOptionPane.showMessageDialog(null, "Se guardo correctamente");
                mostrardatos("");
            }
        } catch (HeadlessException | SQLException e) {
            System.out.print("Error al actualizar: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "No puedes poner una misma Id ya existente ");
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        i = 0;
        TXTIDP.setText("");
        TXTMUEBLE.setText("");
        TXTESTILO.setText("");
        TXTCOLOR.setText("");
        TXTTIPO.setText("");
        Estado.setSelectedIndex(0);
        TXTDESTINO.setText("");
        TXTIDP.setEnabled(true);
        TXTDESTINO.setEnabled(false);
    }//GEN-LAST:event_LimpiarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        mostrardatos(txtBuscar.getText());
    }//GEN-LAST:event_buscarActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        // TODO add your handling code here:
        mostrardatos("");
    }//GEN-LAST:event_MostrarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Home().show();
    }//GEN-LAST:event_RegresarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int fila = tbPedidos.getSelectedRow();
        String cod = "";
        cod = tbPedidos.getValueAt(fila, 0).toString();
        int salida;
        salida = JOptionPane.showConfirmDialog(this, "¿Seguro/a que deseas eliminarlo?", "Confirmar", JOptionPane.OK_CANCEL_OPTION);

        if (salida == 0) {
            //instrucciones
            try {
                String mensaje = "DELETE FROM pedidos_db WHERE Id_pedido='" + cod + "'";
                PreparedStatement pst = cn.prepareStatement(mensaje);
                pst.executeUpdate();
                Cliente c2 = new Cliente(5001, "192.168.0.106", mensaje);
                Thread t2 = new Thread(c2);
                t2.start();
                mostrardatos("");

            } catch (Exception e) {
                System.out.println("No se pudo eliminar" + e);
            }
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public String Clean (String CleanOff){
        String Limpio="";
        Limpio = CleanOff.replaceAll(" ", "");
        return Limpio;
    }
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        i = 1;
        TXTIDP.setEditable(false);
        int fila = tbPedidos.getSelectedRow();
        if (fila >= 0) {
            TXTIDP.setText(Clean(tbPedidos.getValueAt(fila, 0).toString()));
            TXTMUEBLE.setText(Clean(tbPedidos.getValueAt(fila, 1).toString()));
            TXTESTILO.setText(Clean((tbPedidos.getValueAt(fila, 2).toString())));
            TXTCOLOR.setText(Clean(tbPedidos.getValueAt(fila, 3).toString()));
            TXTTIPO.setText(Clean(tbPedidos.getValueAt(fila, 4).toString()));
            Estado.setSelectedItem(Clean(tbPedidos.getValueAt(fila, 5).toString()));
            TXTDESTINO.setText(Clean(tbPedidos.getValueAt(fila, 6).toString()));
        } else {
            JOptionPane.showMessageDialog(null, "no selecciono fila");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public void ACTUALIZAR(){
        try {
             PreparedStatement pst = cn.prepareStatement("UPDATE pedidos_db SET Id_pedido = ?, Mueble = ?, Estilo =?, Color = ?, Tipo_madera = ?, Estado =? , Destino=? WHERE"
                     + " Id_pedido = '"+ TXTIDP.getText()+"'");
            pst.setString(1, TXTIDP.getText());
            pst.setString(2, TXTMUEBLE.getText());
            pst.setString(3, TXTESTILO.getText());
            pst.setString(4, TXTCOLOR.getText());
            pst.setString(5, TXTTIPO.getText());
            pst.setString(6, Estado.getSelectedItem().toString());
            pst.setString(7, TXTDESTINO.getText());
            int i = pst.executeUpdate();
            if (i > 0) {
                JOptionPane.showMessageDialog(null, "Se actualizo correctamente correctamente");
                //socket progracion update to table origen Destino if=muebleriaPaulo o if=muebleriaavila
                mostrardatos("");
            }
        } catch (Exception e) {
            System.out.print("Error al actualizar: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "No se puede modificar Id");

        }
    }
    
    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        String mensaje = "UPDATE pedidos_db SET Id_pedido = '"+ TXTIDP.getText() + "', Mueble = '" + TXTMUEBLE.getText()+ "', "
                + "Estilo = '"+ TXTESTILO.getText()+"', Color = '"+TXTCOLOR.getText()+"', Tipo_madera = '"+TXTTIPO.getText()+"', "
                + "Estado ='"+Estado.getSelectedItem().toString()+"', Destino='"+TXTDESTINO.getText()+"' WHERE"
                     + " Id_pedido = '"+ TXTIDP.getText()+"'";
        TXTIDP.setEditable(true);
        TXTDESTINO.setEditable(true);
        String filial = TXTDESTINO.getText();
        switch (filial) {
            case "Carpinteria_Aserrin":
                Cliente c1 = new Cliente(5001, "192.168.0.106", mensaje);
                Thread t1 = new Thread(c1);
                t1.start();
                ACTUALIZAR();
                break;
            case "Muebleria_Avila":
                ACTUALIZAR();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void TXTIDPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTIDPMousePressed
        // TODO add your handling code here:
        if (evt.getSource() == TXTIDP && i == 1) {
            JOptionPane.showMessageDialog(null, "No se puede modificar Id");
        }
    }//GEN-LAST:event_TXTIDPMousePressed

    private void yih(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yih
        // TODO add your handling code here:
    }//GEN-LAST:event_yih

    private void TXTDESTINOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTDESTINOMousePressed
        // TODO add your handling code here:
        if (evt.getSource() == TXTDESTINO && i == 0) {
            JOptionPane.showMessageDialog(null, "No se puede modificar el destino de origen al registrar");
        }
    }//GEN-LAST:event_TXTDESTINOMousePressed
    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(197, 197, 197));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(240, 240, 240));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Estado;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Mostrar;
    private javax.swing.JButton Regresar;
    private javax.swing.JTextField TXTCOLOR;
    private javax.swing.JTextField TXTDESTINO;
    private javax.swing.JTextField TXTESTILO;
    private javax.swing.JTextField TXTIDP;
    private javax.swing.JTextField TXTMUEBLE;
    private javax.swing.JTextField TXTTIPO;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton buscar;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPedidos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
conexion cc = new conexion();
Connection cn;
}
